### ISSUE TITLE
이거 이렇게 하는게 아니라 

### ISSUE THREAD

**Issue by pmh-only** [1-EXON/All-CODE#2]
![image](https://user-images.githubusercontent.com/39158228/90848178-2f402d00-e3a7-11ea-9d19-8d4c3375479b.png)
![image](https://user-images.githubusercontent.com/39158228/90848356-a1b10d00-e3a7-11ea-823a-e1dd16b59fd6.png)
이 사진처럼 해야됨

**Comment by sihyeokpark** [comment]
ㅇㅎ 그렇군요 잘 알겠슴다
